### ISSUE TITLE
feat: Add History API fallback

### ISSUE THREAD

**Issue by anshumanv** [starkblaze01/git-stalk#10]
- So the browser back button works.
- Stalk links are shareable.

Eg. Try going to - https://github-profile-stalker.netlify.com/stalk/sindresorhus , but works when going from the index page.

**Comment by starkblaze01** [comment]
Hi, @anshumanv Thanks for reporting it. Will work on adding this feature.

**Comment by anshumanv** [comment]
Ok Bova. 🤗

**Comment by starkblaze01** [comment]
Netlify bot was not able to link any URL other than the base to URL to index.html file.
Added `_redirects` file to resolve this.

**Comment by anshumanv** [comment]
Another solution could have been to create a 404.html with the contents of index.html in public dir.

**Comment by starkblaze01** [comment]
🤔I think that still had required to be added in .toml file or _redirects to work.

**Comment by anshumanv** [comment]
No, doesn't need redirect.

**Comment by starkblaze01** [comment]
cool 😁
